/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package brailler;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JRadioButton;

/**
 *
 * @author jonatan
 */
public class AbecedarioFrom extends javax.swing.JFrame {

    /**
     * Creates new form AbecedarioFrom
     */
     MyKeyListener lis= new MyKeyListener();
    public AbecedarioFrom() {
        initComponents();
        setLocationRelativeTo(null);
        addKeyListener(lis);
        this.setFocusable(true);
        background();
        ColorInicial();
    }
    public void ColorInicial(){
        Color colors = new Color(153, 153, 255);
        Fondo.setBackground(new Color(153, 153, 255));
        jRadioButton1.setBackground(new Color(153, 153, 255));
        jRadioButton2.setBackground(new Color(153, 153, 255));
        jRadioButton3.setBackground(new Color(153, 153, 255));
        jRadioButton4.setBackground(new Color(153, 153, 255));
        jRadioButton5.setBackground(new Color(153, 153, 255));
        jRadioButton6.setBackground(new Color(153, 153, 255));
       
        Teclado.setBackground(new Color(153, 76, 255,29));
        Casilla.setBackground(new Color(153, 76, 255,29));
        arrayListBotones();
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i);
            colorBoton(botones.get(i), colors);
            
        }
        
    }
    public Color getColorActual(){
    Color color = Fondo.getBackground();
    return color;
    }
    public void background(){
       Casilla.setBackground(new Color(255,204,0));
       jRadioButton1.setBackground(new Color(255,204,0));
       jRadioButton2.setBackground(new Color(255,204,0));
       jRadioButton3.setBackground(new Color(255,204,0));
       jRadioButton4.setBackground(new Color(255,204,0));
       jRadioButton5.setBackground(new Color(255,204,0));
       jRadioButton6.setBackground(new Color(255,204,0));
    }
public class MyKeyListener implements KeyListener{
//    AbecedarioFrom fm = new AbecedarioFrom();

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
      //  System.out.println(KeyEvent.getKeyText(e.getKeyCode())); 
        char ch = e.getKeyChar();
       // String obtecla =  KeyEvent.getKeyText(e.getKeyCode());
        //System.out.println(obtecla);
        
        if (ch =='a'|| ch =='A') {
           letraA();
        }
        if (ch =='b'|| ch =='B') {
          letraB();
        }
        if (ch =='c'|| ch =='C') {
          letraC();
        }
        if (ch =='d'|| ch =='D') {
          letraD();
        }
        if (ch =='e'|| ch =='E') {
          letraE();
        }
        if (ch =='f'|| ch =='F') {
          letraF();
        }
        if (ch =='g'|| ch =='G') {
          letraG();
        }
        if (ch =='h'|| ch =='H') {
         letraH();
        }
        if (ch =='i'|| ch =='I') {
          letraI();
        }
        if (ch =='j'|| ch =='J') {
          letraJ();
        }
        if (ch =='k'|| ch =='K') {
           letraK();
        }
        if (ch =='l'|| ch =='L') {
          letraL();
        }
        if (ch =='m'|| ch =='M') {
          letraM();
        }
        if (ch =='n'|| ch =='N') {
          letraN();
        }
        if (ch =='ñ'|| ch =='Ñ') {
          letraÑ();
        }
        if (ch =='o'|| ch =='O') {
          letraO();
        }
        if (ch =='p'|| ch =='P') {
          letraP();
        }
        if (ch =='q'|| ch =='Q') {
         letraQ();
        }
        if (ch =='r'|| ch =='R') {
          letraR();
        }
        if (ch =='s'|| ch =='S') {
          letraS();
        }
         if (ch =='t'|| ch =='T') {
          letraT();
        }
        if (ch =='u'|| ch =='U') {
          letraU();
        }
        if (ch =='v'|| ch =='V') {
          letraV();
        }
        if (ch =='w'|| ch =='W') {
          letraW();
        }
        if (ch =='x'|| ch =='X') {
         letraX();
        }
        if (ch =='y'|| ch =='Y') {
          letraY();
        }
        if (ch =='z'|| ch =='Z') {
          letraZ();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Casilla = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        Teclado = new javax.swing.JPanel();
        btA = new javax.swing.JButton();
        btB = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btD = new javax.swing.JButton();
        tdE = new javax.swing.JButton();
        btF = new javax.swing.JButton();
        btG = new javax.swing.JButton();
        btH = new javax.swing.JButton();
        btI = new javax.swing.JButton();
        btJ = new javax.swing.JButton();
        btK = new javax.swing.JButton();
        btL = new javax.swing.JButton();
        btN = new javax.swing.JButton();
        btNN = new javax.swing.JButton();
        btO = new javax.swing.JButton();
        btP = new javax.swing.JButton();
        btQ = new javax.swing.JButton();
        btR = new javax.swing.JButton();
        btS = new javax.swing.JButton();
        btT = new javax.swing.JButton();
        btU = new javax.swing.JButton();
        btV = new javax.swing.JButton();
        btW = new javax.swing.JButton();
        btX = new javax.swing.JButton();
        btY = new javax.swing.JButton();
        btZ = new javax.swing.JButton();
        btM = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        ColorDeCasilla = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        ColorDeFondo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        ColorDeBotones = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        ColorTeclado = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        Casilla.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jRadioButton1.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton1.setBorder(null);
        jRadioButton1.setContentAreaFilled(false);
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setFocusable(false);
        jRadioButton1.setRequestFocusEnabled(false);
        jRadioButton1.setVerifyInputWhenFocusTarget(false);

        jRadioButton2.setBorder(null);
        jRadioButton2.setContentAreaFilled(false);
        jRadioButton2.setFocusPainted(false);
        jRadioButton2.setFocusable(false);
        jRadioButton2.setRequestFocusEnabled(false);
        jRadioButton2.setVerifyInputWhenFocusTarget(false);

        jRadioButton3.setBorder(null);
        jRadioButton3.setContentAreaFilled(false);
        jRadioButton3.setFocusPainted(false);
        jRadioButton3.setFocusable(false);
        jRadioButton3.setRequestFocusEnabled(false);
        jRadioButton3.setVerifyInputWhenFocusTarget(false);

        jRadioButton4.setBorder(null);
        jRadioButton4.setContentAreaFilled(false);
        jRadioButton4.setFocusPainted(false);
        jRadioButton4.setFocusable(false);
        jRadioButton4.setRequestFocusEnabled(false);
        jRadioButton4.setVerifyInputWhenFocusTarget(false);

        jRadioButton5.setBorder(null);
        jRadioButton5.setContentAreaFilled(false);
        jRadioButton5.setFocusPainted(false);
        jRadioButton5.setFocusable(false);
        jRadioButton5.setRequestFocusEnabled(false);
        jRadioButton5.setVerifyInputWhenFocusTarget(false);

        jRadioButton6.setBorder(null);
        jRadioButton6.setContentAreaFilled(false);
        jRadioButton6.setFocusPainted(false);
        jRadioButton6.setFocusable(false);
        jRadioButton6.setRequestFocusEnabled(false);
        jRadioButton6.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout CasillaLayout = new javax.swing.GroupLayout(Casilla);
        Casilla.setLayout(CasillaLayout);
        CasillaLayout.setHorizontalGroup(
            CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasillaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CasillaLayout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton6))
                    .addGroup(CasillaLayout.createSequentialGroup()
                        .addGroup(CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))
                        .addGap(18, 18, 18)
                        .addGroup(CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CasillaLayout.setVerticalGroup(
            CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CasillaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CasillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton6))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Teclado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Teclado"));
        Teclado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btA.setText("A");
        btA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btAMouseReleased(evt);
            }
        });
        btA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAActionPerformed(evt);
            }
        });
        btA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btAFocusGained(evt);
            }
        });
        btA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btAKeyTyped(evt);
            }
        });
        Teclado.add(btA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 40));

        btB.setText("B");
        btB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBActionPerformed(evt);
            }
        });
        btB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btBFocusGained(evt);
            }
        });
        Teclado.add(btB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 40));

        btC.setText("C");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });
        btC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btCFocusGained(evt);
            }
        });
        Teclado.add(btC, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 50, 40));

        btD.setText("D");
        btD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDActionPerformed(evt);
            }
        });
        btD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btDFocusGained(evt);
            }
        });
        Teclado.add(btD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 50, 40));

        tdE.setText("E");
        tdE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdEActionPerformed(evt);
            }
        });
        tdE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdEFocusGained(evt);
            }
        });
        Teclado.add(tdE, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 50, 40));

        btF.setText("F");
        btF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFActionPerformed(evt);
            }
        });
        btF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btFFocusGained(evt);
            }
        });
        Teclado.add(btF, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 50, 40));

        btG.setText("G");
        btG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGActionPerformed(evt);
            }
        });
        btG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btGFocusGained(evt);
            }
        });
        Teclado.add(btG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 40));

        btH.setText("H");
        btH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHActionPerformed(evt);
            }
        });
        btH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btHFocusGained(evt);
            }
        });
        Teclado.add(btH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 50, 40));

        btI.setText("I");
        btI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIActionPerformed(evt);
            }
        });
        btI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btIFocusGained(evt);
            }
        });
        Teclado.add(btI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 50, 40));

        btJ.setText("J");
        btJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJActionPerformed(evt);
            }
        });
        btJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btJFocusGained(evt);
            }
        });
        Teclado.add(btJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 50, 40));

        btK.setText("K");
        btK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKActionPerformed(evt);
            }
        });
        btK.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btKFocusGained(evt);
            }
        });
        Teclado.add(btK, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 50, 40));

        btL.setText("L");
        btL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLActionPerformed(evt);
            }
        });
        btL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btLFocusGained(evt);
            }
        });
        Teclado.add(btL, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 50, 40));

        btN.setText("N");
        btN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNActionPerformed(evt);
            }
        });
        btN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btNFocusGained(evt);
            }
        });
        Teclado.add(btN, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 40));

        btNN.setText("Ñ");
        btNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNNActionPerformed(evt);
            }
        });
        btNN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btNNFocusGained(evt);
            }
        });
        Teclado.add(btNN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 50, 40));

        btO.setText("O");
        btO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOActionPerformed(evt);
            }
        });
        btO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btOFocusGained(evt);
            }
        });
        Teclado.add(btO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 50, 40));

        btP.setText("P");
        btP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPActionPerformed(evt);
            }
        });
        btP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btPFocusGained(evt);
            }
        });
        Teclado.add(btP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 50, 40));

        btQ.setText("Q");
        btQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQActionPerformed(evt);
            }
        });
        btQ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btQFocusGained(evt);
            }
        });
        Teclado.add(btQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 50, 40));

        btR.setText("R");
        btR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRActionPerformed(evt);
            }
        });
        btR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btRFocusGained(evt);
            }
        });
        Teclado.add(btR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 40));

        btS.setText("S");
        btS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSActionPerformed(evt);
            }
        });
        btS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btSFocusGained(evt);
            }
        });
        Teclado.add(btS, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 50, 40));

        btT.setText("T");
        btT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTActionPerformed(evt);
            }
        });
        btT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btTFocusGained(evt);
            }
        });
        Teclado.add(btT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 50, 40));

        btU.setText("U");
        btU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUActionPerformed(evt);
            }
        });
        btU.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btUFocusGained(evt);
            }
        });
        Teclado.add(btU, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, 40));

        btV.setText("V");
        btV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVActionPerformed(evt);
            }
        });
        btV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btVFocusGained(evt);
            }
        });
        Teclado.add(btV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 50, 40));

        btW.setText("W");
        btW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWActionPerformed(evt);
            }
        });
        btW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btWFocusGained(evt);
            }
        });
        Teclado.add(btW, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 50, 40));

        btX.setText("X");
        btX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXActionPerformed(evt);
            }
        });
        btX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btXFocusGained(evt);
            }
        });
        Teclado.add(btX, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 50, 40));

        btY.setText("Y");
        btY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btYActionPerformed(evt);
            }
        });
        btY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btYFocusGained(evt);
            }
        });
        Teclado.add(btY, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 50, 40));

        btZ.setText("Z");
        btZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZActionPerformed(evt);
            }
        });
        btZ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btZFocusGained(evt);
            }
        });
        Teclado.add(btZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 50, 40));

        btM.setText("M");
        btM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMActionPerformed(evt);
            }
        });
        btM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btMFocusGained(evt);
            }
        });
        Teclado.add(btM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 40));

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addComponent(Teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Menu)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addComponent(Casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(Casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu)
                    .addComponent(Teclado, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("Edit");

        jMenuItem1.setText("Color");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Personalizar");

        jMenu4.setText("casilla");

        ColorDeCasilla.setText("Color");
        ColorDeCasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorDeCasillaActionPerformed(evt);
            }
        });
        jMenu4.add(ColorDeCasilla);

        jMenu3.add(jMenu4);
        jMenu3.add(jSeparator1);

        jMenu5.setText("Panel");

        ColorDeFondo.setText("Color");
        ColorDeFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorDeFondoActionPerformed(evt);
            }
        });
        jMenu5.add(ColorDeFondo);

        jMenu3.add(jMenu5);
        jMenu3.add(jSeparator2);

        jMenu6.setText("Botones");

        ColorDeBotones.setText("Color");
        ColorDeBotones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorDeBotonesActionPerformed(evt);
            }
        });
        jMenu6.add(ColorDeBotones);

        jMenuItem9.setText("Color Letra");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem10.setText("Negrita");
        jMenu6.add(jMenuItem10);

        jMenu3.add(jMenu6);

        jMenu7.setText("Teclado");

        ColorTeclado.setText("Color");
        ColorTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorTecladoActionPerformed(evt);
            }
        });
        jMenu7.add(ColorTeclado);

        jMenu3.add(jMenu7);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Ayuda?");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFActionPerformed
        // TODO add your handling code here:
        letraF();
    }//GEN-LAST:event_btFActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        dispose();
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    private void btAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btAMouseReleased

    private void btAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAMouseEntered
            AudioClip A ;
            A = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/A.wav"));
            A.play();
            System.out.println("A");
    }//GEN-LAST:event_btAMouseEntered

    private void btAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btAKeyReleased
         addKeyListener(lis);
    }//GEN-LAST:event_btAKeyReleased

    private void btAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btAKeyTyped
        System.out.println("KeyTyped");
    }//GEN-LAST:event_btAKeyTyped

    private void btAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btAFocusGained
             addKeyListener(lis);
            AudioClip A ;
            A = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/A.wav"));
            A.play();
    }//GEN-LAST:event_btAFocusGained

    private void btBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btBFocusGained
        addKeyListener(lis);
            AudioClip B ;
            B = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/B.wav"));
            B.play();
    }//GEN-LAST:event_btBFocusGained

    private void btCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btCFocusGained
         addKeyListener(lis);  
        AudioClip C ;
            C = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/C.wav"));
            C.play();
    }//GEN-LAST:event_btCFocusGained

    private void btDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btDFocusGained
         addKeyListener(lis);    
        AudioClip D ;
            D = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/D.wav"));
            D.play();
    }//GEN-LAST:event_btDFocusGained

    private void tdEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdEFocusGained
         addKeyListener(lis);
            AudioClip E ;
            E = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/E.wav"));
            E.play();
    }//GEN-LAST:event_tdEFocusGained

    private void btFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btFFocusGained
         addKeyListener(lis);
             AudioClip F ;
            F = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/F.wav"));
            F.play();
    }//GEN-LAST:event_btFFocusGained

    private void btGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btGFocusGained
         addKeyListener(lis);   
        AudioClip G ;
            G = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/G.wav"));
            G.play();
    }//GEN-LAST:event_btGFocusGained

    private void btHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btHFocusGained
         addKeyListener(lis);    
        AudioClip H ; 
            H = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/H.wav"));
            H.play();
    }//GEN-LAST:event_btHFocusGained

    private void btIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btIFocusGained
         addKeyListener(lis);    
        AudioClip I ;
            I = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/I.wav"));
            I.play();
    }//GEN-LAST:event_btIFocusGained

    private void btJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btJFocusGained
         addKeyListener(lis); 
        AudioClip J ;
            J = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/J.wav"));
            J.play();
    }//GEN-LAST:event_btJFocusGained

    private void btKFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btKFocusGained
         addKeyListener(lis);
        AudioClip K ;
            K = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/K.wav"));
            K.play();
    }//GEN-LAST:event_btKFocusGained

    private void btLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btLFocusGained
         addKeyListener(lis);
         AudioClip L ;
            L = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/L.wav"));
            L.play();
    }//GEN-LAST:event_btLFocusGained

    private void btMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btMFocusGained
         addKeyListener(lis);
         AudioClip M ;
            M = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/M.wav"));
            M.play();
    }//GEN-LAST:event_btMFocusGained

    private void btNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btNFocusGained
         addKeyListener(lis);
         AudioClip N ;
            N = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/N.wav"));
            N.play();
    }//GEN-LAST:event_btNFocusGained

    private void btNNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btNNFocusGained
         addKeyListener(lis);
         AudioClip Ñ ;
            Ñ = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/Ñ.wav"));
            Ñ.play();
    }//GEN-LAST:event_btNNFocusGained

    private void btOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btOFocusGained
         addKeyListener(lis);
         AudioClip O ;
            O = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/O.wav"));
            O.play();
    }//GEN-LAST:event_btOFocusGained

    private void btPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btPFocusGained
         addKeyListener(lis);
         AudioClip P ;
            P = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/P.wav"));
            P.play();
    }//GEN-LAST:event_btPFocusGained

    private void btQFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btQFocusGained
         addKeyListener(lis);
         AudioClip Q ;
            Q = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/Q.wav"));
            Q.play();
    }//GEN-LAST:event_btQFocusGained

    private void btTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btTFocusGained
         addKeyListener(lis);
         AudioClip T ;
            T = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/T.wav"));
            T.play();
    }//GEN-LAST:event_btTFocusGained

    private void btUFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btUFocusGained
        addKeyListener(lis);
         AudioClip U ;
            U = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/U.wav"));
            U.play();
    }//GEN-LAST:event_btUFocusGained

    private void btVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btVFocusGained
        addKeyListener(lis);
        AudioClip V ;
            V = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/V.wav"));
            V.play();
    }//GEN-LAST:event_btVFocusGained

    private void btWFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btWFocusGained
         addKeyListener(lis);
         AudioClip W ;
            W = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/W.wav"));
            W.play();
    }//GEN-LAST:event_btWFocusGained

    private void btRFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btRFocusGained
        addKeyListener(lis);
         AudioClip R ;
            R = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/R.wav"));
            R.play();
    }//GEN-LAST:event_btRFocusGained

    private void btSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btSFocusGained
        addKeyListener(lis);
         AudioClip S ;
            S = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/S.wav"));
            S.play();
    }//GEN-LAST:event_btSFocusGained

    private void btXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btXFocusGained
        addKeyListener(lis);
         AudioClip X ;
            X = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/X.wav"));
            X.play();
    }//GEN-LAST:event_btXFocusGained

    private void btYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btYFocusGained
         addKeyListener(lis);
         AudioClip Y ;
            Y = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/Y.wav"));
            Y.play();
    }//GEN-LAST:event_btYFocusGained

    private void btZFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btZFocusGained
         addKeyListener(lis);
         AudioClip Z;
            Z = java.applet.Applet.newAudioClip(getClass().getResource("/Audio/Z.wav"));
            Z.play();
    }//GEN-LAST:event_btZFocusGained

    private void btAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAActionPerformed
      addKeyListener(lis);
        letraA();
    }//GEN-LAST:event_btAActionPerformed

    private void btBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBActionPerformed
        // TODO add your handling code here:
        letraB();
    }//GEN-LAST:event_btBActionPerformed
    public void letraA(){
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraB(){
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
       jRadioButton5.setSelected(false);
       jRadioButton6.setSelected(false);
    }
    public void letraC(){
         jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
       jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(true);
       jRadioButton5.setSelected(false);
       jRadioButton6.setSelected(false);
    }
    public void letraD(){
    jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraE(){
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraF(){
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraG(){
      jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraH(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false); 
    }
    public void letraI(){
     jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraJ(){
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraK(){
      jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraL(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraM(){
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraN(){
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraÑ(){
    jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(true);
    }
    public void letraO(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraP(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraQ(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraR(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraS(){
      jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);
    }
    public void letraT(){
     jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(false);
    }
    public void letraU(){
      jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(true);
    }
    public void letraV(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(true);
    }
    public void letraW(){
         jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(true);
    }
    public void letraX(){
      jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(true);
    }
    public void letraY(){
     jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(true);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(true);
    }
    public void letraZ(){
    jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(true);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(true);
        jRadioButton6.setSelected(true);
    }
    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        letraC();
         addKeyListener(lis);
    }//GEN-LAST:event_btCActionPerformed

    private void btDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDActionPerformed
        letraD();
         addKeyListener(lis);
    }//GEN-LAST:event_btDActionPerformed

    private void tdEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdEActionPerformed
         addKeyListener(lis);
        letraE();
    }//GEN-LAST:event_tdEActionPerformed

    private void btGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGActionPerformed
        addKeyListener(lis);
        letraG();
      
    }//GEN-LAST:event_btGActionPerformed

    private void btHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHActionPerformed
         addKeyListener(lis);
        letraH();
    }//GEN-LAST:event_btHActionPerformed

    private void btIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIActionPerformed
        addKeyListener(lis);
        letraI();
       
    }//GEN-LAST:event_btIActionPerformed

    private void btKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKActionPerformed
         addKeyListener(lis);
        letraK();
    }//GEN-LAST:event_btKActionPerformed

    private void btVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVActionPerformed
         addKeyListener(lis);
        letraV();
    }//GEN-LAST:event_btVActionPerformed

    private void btZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZActionPerformed
        addKeyListener(lis);
        letraZ();
    }//GEN-LAST:event_btZActionPerformed

    private void btJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJActionPerformed
         addKeyListener(lis);
        letraJ();
    }//GEN-LAST:event_btJActionPerformed

    private void btLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLActionPerformed
         addKeyListener(lis);
        letraL();
    }//GEN-LAST:event_btLActionPerformed

    private void btMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMActionPerformed
        addKeyListener(lis);
        letraM();
    }//GEN-LAST:event_btMActionPerformed

    private void btNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNActionPerformed
        addKeyListener(lis);
        letraN();
    }//GEN-LAST:event_btNActionPerformed

    private void btNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNNActionPerformed
       addKeyListener(lis);
        letraÑ();
    }//GEN-LAST:event_btNNActionPerformed

    private void btOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOActionPerformed
        addKeyListener(lis);
        letraO();
    }//GEN-LAST:event_btOActionPerformed

    private void btPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPActionPerformed
        addKeyListener(lis);
        letraP();
    }//GEN-LAST:event_btPActionPerformed

    private void btQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQActionPerformed
        addKeyListener(lis);
        letraQ();
    }//GEN-LAST:event_btQActionPerformed

    private void btTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTActionPerformed
        addKeyListener(lis);
        letraT();
    }//GEN-LAST:event_btTActionPerformed

    private void btUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUActionPerformed
        addKeyListener(lis);
        letraU();
    }//GEN-LAST:event_btUActionPerformed

    private void btWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWActionPerformed
         addKeyListener(lis);
        letraW();
    }//GEN-LAST:event_btWActionPerformed

    private void btRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRActionPerformed
        addKeyListener(lis);
        letraR();
    }//GEN-LAST:event_btRActionPerformed

    private void btSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSActionPerformed
        addKeyListener(lis);
        letraS();
    }//GEN-LAST:event_btSActionPerformed

    private void btXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXActionPerformed
       addKeyListener(lis);
        letraX();
    }//GEN-LAST:event_btXActionPerformed

    private void btYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btYActionPerformed
        addKeyListener(lis);
        letraY();
    }//GEN-LAST:event_btYActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Color actual = Casilla.getBackground();
        /*showDialog(rootPane, null, color); 
        muestra un dialogo de 3 parametros un this , un titulo , color inicial*/
        Color NuevoColor = JColorChooser.showDialog(this, "Cambiar el Color", actual);
        if (NuevoColor !=null) {
            Casilla.setBackground(NuevoColor);
            Fondo.setBackground(NuevoColor);
            Teclado.setBackground(NuevoColor);
            jRadioButton1.setBackground(NuevoColor);
            jRadioButton2.setBackground(NuevoColor);
            jRadioButton3.setBackground(NuevoColor);
            jRadioButton4.setBackground(NuevoColor);
            jRadioButton5.setBackground(NuevoColor);
            jRadioButton6.setBackground(NuevoColor);
          }
                                                
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ColorDeCasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorDeCasillaActionPerformed
        Color actual = Casilla.getBackground();
        Color NuevoColor = JColorChooser.showDialog(this, "Cambiar el Color de Casilla", actual);
        if (NuevoColor !=null) {
            Casilla.setBackground(NuevoColor);
            jRadioButton1.setBackground(NuevoColor);
            jRadioButton2.setBackground(NuevoColor);
            jRadioButton3.setBackground(NuevoColor);
            jRadioButton4.setBackground(NuevoColor);
            jRadioButton5.setBackground(NuevoColor);
            jRadioButton6.setBackground(NuevoColor);
            
          }
    }//GEN-LAST:event_ColorDeCasillaActionPerformed

    private void ColorDeFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorDeFondoActionPerformed
         Color actual = Fondo.getBackground();
        /*showDialog(rootPane, null, color); 
        muestra un dialogo de 3 parametros un this , un titulo , color inicial*/
        Color NuevoColor = JColorChooser.showDialog(this, "Cambiar el Color de Fondo", actual);
        if (NuevoColor !=null) {
            Fondo.setBackground(NuevoColor);
            
          }
    }//GEN-LAST:event_ColorDeFondoActionPerformed
    ArrayList<JButton> botones = new ArrayList<JButton>();
    public void arrayListBotones(){
    botones.add(btA);botones.add(btB);botones.add(btC);botones.add(btD);botones.add(tdE);botones.add(btF);
    botones.add(btG);botones.add(btH);botones.add(btI);botones.add(btJ);botones.add(btK);botones.add(btL);
    botones.add(btM);botones.add(btN);botones.add(btNN);botones.add(btO);botones.add(btP);botones.add(btQ);
    botones.add(btR);botones.add(btS);botones.add(btT);botones.add(btU);botones.add(btV);botones.add(btW);
    botones.add(btX);botones.add(btY);botones.add(btZ);//botones.add(btU);botones.add(btV);botones.add(btW);
    }
    public void colorBoton(JButton btn,Color color){
        btn.setBackground(color);
    }
    private void ColorDeBotonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorDeBotonesActionPerformed
         arrayListBotones();
         Color actual = btA.getBackground();
         Color NuevoColor = JColorChooser.showDialog(this, "Cambiar el Color Botones", actual);
         if (NuevoColor != null){
         for (int i = 0; i < botones.size(); i++) {
            botones.get(i);
             colorBoton(botones.get(i), NuevoColor);
        }
       }
        
    }//GEN-LAST:event_ColorDeBotonesActionPerformed

    private void ColorTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorTecladoActionPerformed
         Color actual = Teclado.getBackground();
        Color NuevoColor = JColorChooser.showDialog(this, "Cambiar el Color Teclado", actual);
        if (NuevoColor !=null) {
            Teclado.setBackground(NuevoColor);
            
          }
    }//GEN-LAST:event_ColorTecladoActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FondoLetra();
    }//GEN-LAST:event_jMenuItem9ActionPerformed
    public void FondoLetra(){
         Color actual = btA.getForeground();
         Color NuevoColor = JColorChooser.showDialog(this, "Cambiar el Color de Letra", actual);
         arrayListBotones();
         for (int i = 0; i < botones.size(); i++) {
            botones.get(i);
            EditarText(botones.get(i), NuevoColor);
        }
    }
    public void EditarText(JButton btc,Color color){
        btc.setForeground(color);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbecedarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbecedarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbecedarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbecedarioFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AbecedarioFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Casilla;
    private javax.swing.JMenuItem ColorDeBotones;
    private javax.swing.JMenuItem ColorDeCasilla;
    private javax.swing.JMenuItem ColorDeFondo;
    private javax.swing.JMenuItem ColorTeclado;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Menu;
    private javax.swing.JPanel Teclado;
    private javax.swing.JButton btA;
    private javax.swing.JButton btB;
    private javax.swing.JButton btC;
    private javax.swing.JButton btD;
    private javax.swing.JButton btF;
    private javax.swing.JButton btG;
    private javax.swing.JButton btH;
    private javax.swing.JButton btI;
    private javax.swing.JButton btJ;
    private javax.swing.JButton btK;
    private javax.swing.JButton btL;
    private javax.swing.JButton btM;
    private javax.swing.JButton btN;
    private javax.swing.JButton btNN;
    private javax.swing.JButton btO;
    private javax.swing.JButton btP;
    private javax.swing.JButton btQ;
    private javax.swing.JButton btR;
    private javax.swing.JButton btS;
    private javax.swing.JButton btT;
    private javax.swing.JButton btU;
    private javax.swing.JButton btV;
    private javax.swing.JButton btW;
    private javax.swing.JButton btX;
    private javax.swing.JButton btY;
    private javax.swing.JButton btZ;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton tdE;
    // End of variables declaration//GEN-END:variables
}
